Issue #293 sort
the-clothing-loop/website pull request #361
Opened 2023-02-06 06:24 UTC by jnorlando

2023-02-07 10:08 UTC, lil5 requested changes
Great draggable function! Is that a in build react util or is there a `npm` dependency I'm not seeing?

2023-02-07 10:58 UTC, lil5 commented on server/internal/models/chain.go
> +	Route 				   []string `gorm:"serializer:json; default:[]"`
I know this is a little sudden, I'm currently reading **SQL Antipatterns** and this was a good example of the **Format Comma-Seperated Lists** which is an antipattern when referencing other tables. 

More information: https://github.com/boralp/sql-anti-patterns#store-each-value-in-its-own-column-and-row

I'm mostly interested in **1. Creating a column in user_chains**

2023-02-07 16:09 UTC, jnorlando commented on frontend/package.json
> +    "i": "^0.3.7",
it's built in

2023-02-07 16:11 UTC, jnorlando commented on frontend/package.json
> +    "i": "^0.3.7",
draggable is built into react

2023-02-13 16:55 UTC, jnorlando commented
Going to try to get the current revisions done between tonight and tomorrow; @lil5 Though, I'd advise not bothering to do another review of it until check-box is merged, since i'll want to sync main with the sort-fork, in order to make sure everything is still functioning as it should.

2023-02-13 20:37 UTC, merged