Created api call to find chains near a location
the-clothing-loop/website pull request #597
Opened 2023-09-17 00:58 UTC by NeedADispenserHere

API endpoint is /v2/chain/near?longitude=x&latitude=y&radius=z

2023-09-17 09:28 UTC, lil5 requested changes
Thanks for the PR, some change requests - I'm in the train 🚊 atm I'll test the `where` location tomorrow.

2023-09-17 09:28 UTC, lil5 commented on server/internal/controllers/chain.go
> +		Radius    float32 `form:"radius" binding:"required,longitude"`
Remove the longitude from the binding

2023-09-17 09:28 UTC, lil5 commented on server/internal/controllers/chain.go
> +	sql = fmt.Sprintf("%s WHERE %s <= ? ", sql, sqlCalcDistance("chains.latitude", "chains.longitude", "?", "?"))
Filter out unpublished loops

2023-09-17 09:28 UTC, lil5 commented on server/internal/controllers/chain.go
> +			"open_to_new_members": chain.OpenToNewMembers,
To show a list of loops that are nearby only the name, genders and uid (for links) is required you can also sharpen the `select *`

2023-10-30 07:12 UTC, NeedADispenserHere commented
I've applied the requested changes

2023-11-03 12:39 UTC, merged

2023-11-03 12:42 UTC, lil5 commented
Accepted I tried it out in Bruno and it worked great!